library(dplyr)
library(ggplot2)
library(ggeffects)
library(ggpubr)
library(multcomp)
library(multcompView)
library(raster)
library(emmeans)
library(tidyverse)
library(lme4)
library(readxl)
library(cowplot)
library(gtsummary)
library(MASS)
library(broom)

## set working directory, Load in Data

#I'd always recommend setting working directory,
#to cover yourself! also, stringAsFactors will get
#all of those columns as factors :) 
setwd("C:/Users/Tesia/Documents/R/FernWork/")
dat <- read.csv("BartFieldWorking.csv",
stringsAsFactors = TRUE)
View(dat)
#I always like to view the data to make sure eveyrthing
#looks fine in the chart generated by R

#-----------------------------------------------
##remove NAs from dataset, I think this will be
#in all the the climate stuff, so subset to either
#2015Rain or #MeanRain
cleandat <- subset(dat, dat$Rain2015 !="NA" | 
                   dat$MeanRain !="NA")
cleandat <- cleandat %>% mutate(LogGerm = log(cleandat$Germinate))
view(cleandat)

#FIRSTONE--looking at all of the data with home and site, population is
#the degree of variance
GenMod <- glm(LogGerm ~ Home + Site + (1|Population),
               data = cleandat,
               family = binomial)
summary(GenMod)

#subset data where germination does not = 0 by first mutating
#all values > 0 into just 1
hurDat <- cleandat %>% mutate(GermBin = ifelse(Germinate > 0, 1, 0)) %>% 
  filter(GermBin > 0)
view(hurDat)
#use that new column of germination binary for a binary model where
#germination does not equal 0: 
AbunMod <- glm.nb(LogGerm ~ Home + Site + Population,  
                  data = hurDat)
anoMod <- anova(AbunMod)
view(anoMod)
plot(anoMod)

#view the summary of the model and compare to paper if provided
summary(AbunMod)
plot(AbunMod)
#you don't actually need this plot, I just like looking

#ESTABLISHMENT SHOWING EVIDENCE OF LOCAL ADAPTATION
#This one I'm a little unsure of, it definitely uses the 
#previous data that eliminates where the outplantings didn't germinate
EstMod <- glm.nb(Establish ~ Home + Population + Site, 
                            data = hurDat)
summary(EstMod)
plot(EstMod) #again you don't actually need this, I just like looking
#----------------------------------------------


